#We are using Spark Reporter and create 'Report' folder and create output 'Spark.html' report file
extent.reporter.spark.start=true
extent.reporter.spark.out=Report/Spark.html


#This is for screenshots configuration
screenshot.dir=Screenshots/
screenshot.rel.path=../Screenshots/

#Customize the report folder name by adding folder name and non repeating pattern
basefolder.name=test-output/SparkReport
basefolder.datetimepattern=d-MMM-YY HH-mm-ss

